import "Cenedes.ViewModels.idl";

namespace Cenedes.ViewModels
{
    [bindable]
    [default_interface]
    runtimeclass ClinicalReport : IModel, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        ClinicalReport();
    }
}
