import "Cenedes.ViewModels.idl";
import "Cenedes.ViewModels.Patient.idl";
import "Cenedes.ViewModels.Clinic.idl";

namespace Cenedes.ViewModels
{
    [bindable]
    [default_interface]
    runtimeclass PatientClinic : IModel, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        PatientClinic();
        UInt64  PatientClinicId;

        UInt64  PatientId;
        Patient Patient;

        UInt64  ClinicId;
        Clinic  Clinic;
    }
}
