import "Cenedes.ViewModels.idl";

namespace Cenedes.ViewModels
{
    [bindable]
    [default_interface]
    runtimeclass Exam : IModel, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        Exam();
    }
}
