import "Cenedes.ViewModels.idl";

namespace Cenedes.ViewModels
{
    [bindable]
    [default_interface]
    runtimeclass Nurse : IModel, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        Nurse();
    }
}
