import "Cenedes.ViewModels.idl";

namespace Cenedes.ViewModels
{
    [bindable]
    [default_interface]
    runtimeclass Clinic : IModel
    {
        Clinic();
        UInt64 ClinicId;
        String Name;
        String Phone;
        String Address;
    }
}
