import "Cenedes.ViewModels.idl";
import "Cenedes.ViewModels.Types.idl";
import "Cenedes.ViewModels.Patient.idl";

namespace Cenedes.ViewModels
{
    [bindable]
    [default_interface]
    runtimeclass Prescription : IModel, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        Prescription();

        UInt64   PrescriptionId;
        UInt64   ConsultId;
        UInt64   PatientId;
        Patient  Patient;
        DateTime PrescriptionDate;
    }
}
