import "Cenedes.ViewModels.idl";
import "Cenedes.ViewModels.Types.idl";

namespace Cenedes.ViewModels
{
    [bindable]
    [default_interface]
    runtimeclass PrescriptionDetails : IModel, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        PrescriptionDetails();

        UInt64   PrescriptionId;
        String   Medicine;
        String   MedicineDetails;
        DateTime BeginDate;
        DateTime EndDate;

        Windows.Foundation.IReference<UInt32> MedicineAmountPerDay;
        Windows.Foundation.IReference<TimeSpan> TimeTakeMedicine;
    }
}
