import "Cenedes.ViewModels.idl";

namespace Cenedes.ViewModels
{
    [bindable]
    [default_interface]
    runtimeclass Epicrisis : IModel, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        Epicrisis();
    }
}
