import "Cenedes.ViewModels.idl";

namespace Cenedes.ViewModels
{
    [bindable]
    [default_interface]
    runtimeclass Person : IModel, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        Person();
    }
}
