import "Cenedes.ViewModels.idl";

namespace Cenedes.ViewModels
{
    [bindable]
    [default_interface]
    runtimeclass MedicalSchedule : IModel, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        MedicalSchedule();
    }
}
