namespace Cenedes.Application
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();
        Microsoft.UI.Xaml.Controls.Frame ContentFrame { get; };
        Microsoft.UI.Windowing.AppWindow MainAppWindow { get; };
    }
}